/**
 * Type definitions for the Mosaic REST API.
 * Extracted from @mosaic/api to keep the MCP server self-contained.
 */

// ── Common ───────────────────────────────────────────
export interface PaginatedResponse<T> {
  items: T[]
  total: number
  page: number
  pageSize: number
  totalPages: number
}

// ── Auth ─────────────────────────────────────────────
export interface LoginResponse {
  accessToken: string
  refreshToken: string
  user: {
    id: string
    username: string
    avatarUrl?: string
  }
}

// ── Memos ────────────────────────────────────────────
export interface Memo {
  id: string
  content: string
  tags: string[]
  isArchived: boolean
  diaryDate?: string
  aiSummary?: string
  resources?: Resource[]
  createdAt: number
  updatedAt: number
  revisionCount: number
  semanticScore?: number
  keywordScore?: number
  matchType?: 'keyword' | 'semantic' | 'hybrid'
}

export type MemoResponse = Memo
export type MemoWithResourcesResponse = Memo

export interface ListMemosQuery {
  page?: number
  pageSize?: number
  archived?: boolean
  diaryDate?: string
  [key: string]: unknown
}

export interface CreateMemoRequest {
  content: string
  tags?: string[]
  resourceIds?: string[]
  diaryDate?: string
  aiSummary?: string
}

export interface UpdateMemoRequest {
  content?: string
  tags?: string[]
  resourceIds?: string[]
  isArchived?: boolean
  diaryDate?: string | null
  aiSummary?: string | null
}

export interface SearchMemosQuery {
  query: string
  tags?: string[]
  startDate?: string
  endDate?: string
  isArchived?: boolean
  page?: number
  pageSize?: number
  [key: string]: unknown
}

export interface SearchMemosResponse {
  memos: Memo[]
  total: number
  page: number
  pageSize: number
  semanticEnabled: boolean
}

export interface TagResponse {
  tag: string
  count: number
}

export interface ClipRequest {
  clipType: 'url' | 'text' | 'image'
  url?: string
  content?: string
  resourceId?: string
  userNote?: string
}

export interface ClipResult {
  title: string
  content: string
  aiSummary: string
  tags: string[]
  sourceUrl: string | null
  sourceType: string
  originalTitle: string | null
}

// ── Diaries ──────────────────────────────────────────
export type MoodKey =
  | 'joy'
  | 'calm'
  | 'neutral'
  | 'sadness'
  | 'anxiety'
  | 'anger'
  | 'focus'
  | 'tired'

export interface Diary {
  date: string
  summary: string
  moodKey: MoodKey
  moodScore: number
  generationSource: string
  autoGenerationLocked: boolean
  generatedFromMemoIds: string[]
  lastAutoGeneratedAt?: number
  createdAt: number
  updatedAt: number
}

export type DiaryResponse = Diary

export interface DiaryWithMemosResponse {
  date: string
  summary: string
  moodKey: MoodKey
  moodScore: number
  memos: MemoWithResourcesResponse[]
  createdAt: number
  updatedAt: number
}

export interface ListDiariesQuery {
  page?: number
  pageSize?: number
  startDate?: string
  endDate?: string
  [key: string]: unknown
}

export interface CreateDiaryRequest {
  date: string
  summary: string
  moodKey: MoodKey
  moodScore?: number
}

export interface UpdateDiaryRequest {
  summary?: string
  moodKey?: MoodKey
  moodScore?: number
}

// ── Bots ─────────────────────────────────────────────
export interface Bot {
  id: string
  name: string
  avatarUrl?: string
  description: string
  tags: string[]
  autoReply: boolean
  sortOrder: number
  model?: string
  aiConfig?: Record<string, unknown>
  createdAt: number
  updatedAt: number
  memoryStats?: {
    totalContextsBuilt: number
    lastContextAt: number | null
  }
}

export interface BotReply {
  id: string
  memoId: string
  bot: { id: string; name: string; avatarUrl?: string }
  content: string
  thinkingContent?: string
  parentReplyId: string | null
  userQuestion: string | null
  revisionNumber: number | null
  createdAt: number
  children: BotReply[]
  threadCount: number
  latestReplyId: string
}

export interface BotThreadMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  thinkingContent?: string
  resourceIds: string[]
  createdAt: number
}

export interface BotThread {
  memoId: string
  bot: { id: string; name: string; avatarUrl?: string }
  messages: BotThreadMessage[]
  latestReplyId: string
}

// ── Memory ───────────────────────────────────────────
export interface MemoryStats {
  totalMemos: number
  indexedMemos: number
}

export interface MemoryActivityEntry {
  id: string
  botId: string
  botName: string
  memoId: string
  retrievedCount: number
  promptSize: number
  createdAt: number
}

export interface RetrievedMemoItem {
  id: string
  excerpt: string
  score: number
  reason: string
  createdAt: number
}

export interface MemoryContext {
  retrievedMemos: RetrievedMemoItem[]
}

export interface MemoContextsResponse {
  contexts: Record<string, MemoryContext>
}

// ── Stats ────────────────────────────────────────────
export interface StatsQuery {
  startDate: string
  endDate: string
  [key: string]: unknown
}

export interface SummaryQuery {
  year: number
  month: number
  [key: string]: unknown
}

export interface HeatMapData {
  dates: string[]
  counts: number[]
  moods: (MoodKey | null)[]
  moodScores: (number | null)[]
}

export interface TimelineEntry {
  date: string
  moodKey: MoodKey | null
  moodScore: number | null
  summary: string
  memoCount: number
  color: string
}

export interface TimelineData {
  entries: TimelineEntry[]
}

export interface MoodData {
  moodKey: MoodKey
  count: number
  percentage: number
}

export interface TagData {
  tag: string
  count: number
}

export interface TrendsData {
  moods: MoodData[]
  tags: TagData[]
}

export interface SummaryData {
  totalMemos: number
  totalDiaries: number
  totalResources: number
}

// ── Resources ────────────────────────────────────────
export type ResourceType = 'image' | 'video'

export interface ResourceMetadata {
  width?: number
  height?: number
  durationMs?: number
  thumbnailTimeMs?: number
}

export interface Resource {
  id: string
  memoId: string | null
  filename: string
  resourceType: ResourceType
  mimeType: string
  fileSize: number
  storageType: string
  url: string
  thumbnailUrl?: string
  metadata: ResourceMetadata
  createdAt: number
}

export type ResourceResponse = Resource

// ── Admin ────────────────────────────────────────────
export interface ServerAiConfig {
  key: 'bot' | 'embedding'
  provider: string
  baseUrl: string
  apiKey: string
  model: string
  temperature?: number
  maxTokens?: number
  timeoutSeconds?: number
  supportsVision: boolean
  supportsThinking: boolean
  embeddingDim?: number
  updatedAt: number
}

export interface ServerAiConfigPayload {
  provider: string
  baseUrl: string
  apiKey: string
  model: string
  temperature?: number
  maxTokens?: number
  timeoutSeconds?: number
  supportsVision?: boolean
  supportsThinking?: boolean
  embeddingDim?: number
}

export interface AdminAiConfigResponse {
  bot: ServerAiConfig
  embedding: ServerAiConfig
}
