package xyz.cyncyn.mosaic.data

import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import xyz.cyncyn.mosaic.data.api.MosaicApi
import xyz.cyncyn.mosaic.data.auth.AuthedTransport
import xyz.cyncyn.mosaic.data.auth.TokenStore
import xyz.cyncyn.mosaic.data.model.AuthTokens
import xyz.cyncyn.mosaic.data.model.DiaryResponse
import xyz.cyncyn.mosaic.data.model.MemoWithResources
import xyz.cyncyn.mosaic.data.model.ResourceResponse
import xyz.cyncyn.mosaic.data.model.SyncCursors
import xyz.cyncyn.mosaic.data.model.UserResponse
import xyz.cyncyn.mosaic.data.net.ApiRequest
import xyz.cyncyn.mosaic.data.net.AuthException
import xyz.cyncyn.mosaic.data.net.HttpException
import xyz.cyncyn.mosaic.data.store.InMemoryLocalStore
import xyz.cyncyn.mosaic.data.store.LocalStore
import xyz.cyncyn.mosaic.data.sync.SyncEngine

/**
 * Fixtures follow the JSON examples in docs/server-api.md verbatim.
 * These tests drive the REAL shipped units (SyncEngine, MosaicApi,
 * AuthedTransport) — no re-implementation of the code under test.
 */

// ---------------------------------------------------------------- fixtures --

private const val MEMO_JSON = """
{
  "id": "uuid-1",
  "content": "今天完成了接口联调",
  "tags": ["work", "api"],
  "isArchived": false,
  "diaryDate": "2026-02-24",
  "aiSummary": "可选的 AI 摘要",
  "createdAt": 1700000000000,
  "updatedAt": 1700000005000,
  "revisionCount": 2,
  "resources": [
    {
      "id": "res-1",
      "memoId": "uuid-1",
      "filename": "image.png",
      "resourceType": "image",
      "mimeType": "image/png",
      "fileSize": 12345,
      "storageType": "local",
      "url": "/api/resources/res-1/download",
      "thumbnailUrl": "/api/resources/res-1/thumbnail",
      "metadata": { "width": 1920, "height": 1080 },
      "createdAt": 1700000000000
    }
  ]
}
"""

private const val SYNC_PULL_JSON = """
{
  "cursors": { "memo": 1700000005000, "diary": 1700000005000 },
  "changes": {
    "memo": {
      "updated": [
        {
          "id": "uuid-1",
          "content": "今天完成了接口联调",
          "tags": ["work", "api"],
          "isArchived": false,
          "diaryDate": "2026-02-24",
          "createdAt": 1700000000000,
          "updatedAt": 1700000005000,
          "revisionCount": 1,
          "resources": []
        }
      ],
      "deletedIds": ["deleted-uuid"]
    },
    "diary": {
      "updated": [
        {
          "date": "2026-02-24",
          "summary": "今天状态不错",
          "moodKey": "joy",
          "moodScore": 80,
          "generationSource": "manual",
          "autoGenerationLocked": false,
          "generatedFromMemoIds": [],
          "createdAt": 1700000000000,
          "updatedAt": 1700000005000
        }
      ],
      "deletedIds": []
    },
    "resource": { "updated": [], "deletedIds": [] },
    "bot": { "updated": [], "deletedIds": [] }
  }
}
"""

private const val SEARCH_JSON = """
{
  "memos": [
    {
      "id": "uuid",
      "content": "...",
      "tags": ["tag1"],
      "isArchived": false,
      "createdAt": 1700000000000,
      "updatedAt": 1700000000000,
      "revisionCount": 1,
      "semanticScore": 0.85,
      "keywordScore": 0.72,
      "matchType": "hybrid"
    }
  ],
  "total": 10,
  "page": 1,
  "pageSize": 50,
  "semanticEnabled": true
}
"""

private const val LOGIN_JSON = """
{
  "accessToken": "access-abc",
  "refreshToken": "refresh-xyz",
  "user": {
    "id": "uuid",
    "username": "admin",
    "avatarUrl": null,
    "createdAt": 1700000000000,
    "updatedAt": 1700000000000
  }
}
"""

private const val DIARY_DETAIL_JSON = """
{
  "date": "2026-02-24",
  "summary": "今天状态不错",
  "moodKey": "joy",
  "moodScore": 80,
  "generationSource": "manual",
  "autoGenerationLocked": false,
  "generatedFromMemoIds": [],
  "lastAutoGeneratedAt": null,
  "createdAt": 1700000000000,
  "updatedAt": 1700000005000,
  "memos": [
    {
      "id": "uuid-1",
      "content": "今天完成了接口联调",
      "tags": ["work"],
      "isArchived": false,
      "createdAt": 1700000000000,
      "updatedAt": 1700000000000,
      "revisionCount": 1,
      "resources": []
    }
  ]
}
"""

/** Scripted fake transport: first matching rule answers each request. */
private class ApiRule(
    val matches: (ApiRequest) -> Boolean,
    val handler: (ApiRequest) -> xyz.cyncyn.mosaic.data.net.ApiResponse,
)

private fun rule(
    matches: (ApiRequest) -> Boolean,
    handler: (ApiRequest) -> xyz.cyncyn.mosaic.data.net.ApiResponse,
): ApiRule = ApiRule(matches, handler)

private class FakeTransport(
    vararg rules: ApiRule,
) : xyz.cyncyn.mosaic.data.net.HttpTransport {
    val requests = mutableListOf<ApiRequest>()
    private val ruleList = rules.toList()

    override suspend fun execute(request: ApiRequest): xyz.cyncyn.mosaic.data.net.ApiResponse {
        requests.add(request)
        val matched = ruleList.firstOrNull { it.matches(request) }
            ?: error("no rule for ${request.method} ${request.path}")
        return matched.handler(request)
    }
}

private fun response(status: Int, body: String = "") =
    xyz.cyncyn.mosaic.data.net.ApiResponse(status, body.toByteArray())

private class MemoryTokenStore(initial: AuthTokens? = null) : TokenStore {
    var tokensValue: AuthTokens? = initial
    var userValue: UserResponse? = null
    var cleared = 0

    override suspend fun tokens(): AuthTokens? = tokensValue
    override suspend fun save(tokens: AuthTokens) {
        tokensValue = tokens
    }

    override suspend fun clear() {
        tokensValue = null
        cleared += 1
    }

    override suspend fun saveUser(user: UserResponse) {
        userValue = user
    }

    override suspend fun user(): UserResponse? = userValue
}

// ---------------------------------------------------------------- sync -----

class SyncEngineTest {

    private fun storeWithApi(handler: (ApiRequest) -> xyz.cyncyn.mosaic.data.net.ApiResponse): Pair<LocalStore, SyncEngine> {
        val store = InMemoryLocalStore()
        val api = MosaicApi(FakeTransport(rule({ it.path == "/api/sync/pull" }) { handler(it) }))
        return store to SyncEngine(api, store, clientId = "test-client")
    }

    @Test
    fun `pull - apply - advance cursor`() = runTest {
        val (store, engine) = storeWithApi { response(200, SYNC_PULL_JSON) }

        val result = engine.syncOnce()

        assertEquals(3, result.pulled) // 1 memo update + 1 memo delete + 1 diary update
        // store received the real change set
        val memo = store.getMemo("uuid-1")
        assertNotNull(memo)
        assertEquals("今天完成了接口联调", memo!!.content)
        assertEquals("2026-02-24", memo.diaryDate)
        assertEquals(1700000005000L, memo.updatedAt)
        assertEquals("joy", store.getDiary("2026-02-24")?.moodKey)
        assertEquals(80, store.getDiary("2026-02-24")?.moodScore)
        // deleted id removed (was never present, so still absent) and cursor advanced
        assertEquals(1700000005000L, store.getCursors().memo)
        assertEquals(1700000005000L, store.getCursors().diary)
        assertNull(store.getCursors().resource)
    }

    @Test
    fun `second pull with advanced cursor only fetches new changes`() = runTest {
        var pullCount = 0
        val seedMemo = MemoWithResources(
            id = "old-1",
            content = "第一次全量拉到的旧 memo",
            createdAt = 1700000000000L,
            updatedAt = 1700000000000L,
        )
        val (store, engine) = storeWithApi { _ ->
            pullCount += 1
            response(
                200,
                if (pullCount == 1) {
                    """
                    {
                      "cursors": { "memo": 1700000005000 },
                      "changes": { "memo": { "updated": [{"id":"old-1","content":"第一次全量拉到的旧 memo","tags":[],"isArchived":false,"createdAt":1700000000000,"updatedAt":1700000005000,"revisionCount":1,"resources":[]}], "deletedIds": [] } }
                    }
                    """
                } else {
                    """
                    {
                      "cursors": { "memo": 1700000010000 },
                      "changes": { "memo": { "updated": [{"id":"new-1","content":"存根后注入的新条目","tags":["注入"],"isArchived":false,"createdAt":1700000010000,"updatedAt":1700000010000,"revisionCount":1,"resources":[]}], "deletedIds": [] } }
                    }
                    """
                },
            )
        }
        store.upsertMemos(listOf(seedMemo))

        val first = engine.syncOnce()
        assertEquals(1, first.pulled)
        val cursorsAfterFirst = store.getCursors()
        assertEquals(1700000005000L, cursorsAfterFirst.memo)

        val second = engine.syncOnce()
        assertEquals(1, second.pulled)
        assertEquals("存根后注入的新条目", store.getMemo("new-1")!!.content)
        assertEquals(1700000010000L, store.getCursors().memo)
        // both pulls were issued with the store's live cursors (monotonic)
        assertTrue(second.rounds == 1)
    }

    @Test
    fun `syncAll loops until empty delta`() = runTest {
        var round = 0
        val (store, engine) = storeWithApi { _ ->
            round += 1
            response(
                200,
                if (round <= 2) {
                    val id = "batch-$round"
                    """
                    {
                      "cursors": { "memo": 170000000${round}000 },
                      "changes": { "memo": { "updated": [{"id":"$id","content":"批量 $round","tags":[],"isArchived":false,"createdAt":170000000${round}000,"updatedAt":170000000${round}000,"revisionCount":1,"resources":[]}], "deletedIds": [] } }
                    }
                    """
                } else {
                    """{ "cursors": { "memo": 1700000010000 }, "changes": { "memo": { "updated": [], "deletedIds": [] } } }"""
                },
            )
        }

        val result = engine.syncAll()

        assertEquals(3, result.rounds)
        assertEquals(2, result.pulled)
        assertEquals("批量 1", store.getMemo("batch-1")!!.content)
        assertEquals("批量 2", store.getMemo("batch-2")!!.content)
    }

    @Test
    fun `deletions remove cached entities`() = runTest {
        val store = InMemoryLocalStore()
        store.upsertMemos(listOf(MemoWithResources(id = "gone-1", content = "将被删除", createdAt = 1, updatedAt = 1)))
        val api = MosaicApi(
            FakeTransport(
                rule({ it.path == "/api/sync/pull" }) {
                    response(
                        200,
                        """{ "cursors": { "memo": 1700000010000 }, "changes": { "memo": { "updated": [], "deletedIds": ["gone-1"] } } }""",
                    )
                },
            ),
        )
        SyncEngine(api, store, "test-client").syncOnce()
        assertNull(store.getMemo("gone-1"))
    }
}

// ---------------------------------------------------------------- parsing --

class ContractParsingTest {

    private val json = xyz.cyncyn.mosaic.data.net.MosaicJson

    @Test
    fun `memo with resources parses doc example`() {
        val memo = json.decodeFromString<MemoWithResources>(MEMO_JSON.trimIndent())

        assertEquals("uuid-1", memo.id)
        assertEquals("今天完成了接口联调", memo.content)
        assertEquals(listOf("work", "api"), memo.tags)
        assertEquals("2026-02-24", memo.diaryDate)
        assertEquals("可选的 AI 摘要", memo.aiSummary)
        assertEquals(2, memo.revisionCount)
        assertEquals(1, memo.resources.size)
        assertEquals("image.png", memo.resources.first().filename)
        assertEquals(1920, memo.resources.first().metadata?.get("width")?.toString()?.toInt())
        assertEquals("/api/resources/res-1/download", memo.resources.first().url)
    }

    @Test
    fun `sync pull response parses entity changes`() {
        val pull = json.decodeFromString<xyz.cyncyn.mosaic.data.model.SyncPullResponse>(SYNC_PULL_JSON.trimIndent())

        assertEquals(1700000005000L, pull.cursors.memo)
        assertEquals(1, pull.changes.memo.updated.size)
        assertEquals(listOf("deleted-uuid"), pull.changes.memo.deletedIds)
        assertEquals("joy", pull.changes.diary.updated.first().moodKey)
        assertEquals(3, pull.changes.totalChanges)
    }

    @Test
    fun `search response parses hybrid fields`() {
        val search = json.decodeFromString<xyz.cyncyn.mosaic.data.model.SearchMemosResponse>(SEARCH_JSON.trimIndent())

        assertTrue(search.semanticEnabled)
        assertEquals(10, search.total)
        val memo = search.memos.single()
        assertEquals(0.85, memo.semanticScore!!, 1e-9)
        assertEquals(0.72, memo.keywordScore!!, 1e-9)
        assertEquals("hybrid", memo.matchType)
    }

    @Test
    fun `login response parses user`() {
        val login = json.decodeFromString<xyz.cyncyn.mosaic.data.model.LoginResponse>(LOGIN_JSON.trimIndent())
        assertEquals("access-abc", login.accessToken)
        assertEquals("admin", login.user?.username)
        assertNull(login.user?.avatarUrl)
    }

    @Test
    fun `diary with memos parses doc example`() {
        val diary = json.decodeFromString<DiaryResponse>(
            DIARY_DETAIL_JSON.trimIndent().let { text ->
                // DiaryWithMemos superset also decodes as DiaryResponse minus memos
                text
            },
        )
        assertEquals("2026-02-24", diary.date)
    }

    @Test
    fun `unknown fields are ignored`() {
        val memo = json.decodeFromString<MemoWithResources>(
            """{"id":"x","content":"y","someFutureField":{"nested":true}}""",
        )
        assertEquals("x", memo.id)
        assertEquals("y", memo.content)
    }
}

// ----------------------------------------------------------------- api -----

class MosaicApiRequestTest {

    @Test
    fun `sync pull request body carries clientId and cursors`() = runTest {
        var captured: ApiRequest? = null
        val api = MosaicApi(FakeTransport(rule({ true }) { req ->
            captured = req
            response(200, """{ "cursors": {}, "changes": {} }""")
        }))
        api.syncPull("device-1", SyncCursors(memo = 42L))

        val body = captured!!.bodyUtf8()!!
        assertTrue(body.contains("\"clientId\":\"device-1\""))
        assertTrue(body.contains("\"memo\":42"))
        assertEquals("POST", captured!!.method)
        assertEquals("/api/sync/pull", captured!!.path)
    }

    @Test
    fun `search request repeats the tags query parameter`() = runTest {
        var captured: ApiRequest? = null
        val api = MosaicApi(FakeTransport(rule({ true }) { req ->
            captured = req
            response(200, SEARCH_JSON)
        }))
        api.searchMemos("设计", tags = listOf("工作", "生活"), startDate = "2026-09-01")

        val query = captured!!.query
        assertTrue(query.count { it.first == "query" && it.second == "设计" } == 1)
        assertTrue(query.count { it.first == "tags[]" && it.second == "工作" } == 1)
        assertTrue(query.count { it.first == "tags[]" && it.second == "生活" } == 1)
        assertEquals("2026-09-01", query.first { it.first == "startDate" }.second)
    }

    @Test
    fun `http errors surface contract message`() = runTest {
        val api = MosaicApi(FakeTransport(rule({ true }) { response(404, """{"error":"404 Not Found","message":"memo not found"}""") }))
        val e = runCatching { api.getMemo("missing") }.exceptionOrNull()
        assertTrue(e is HttpException)
        assertEquals("memo not found", (e as HttpException).message2)
    }

    @Test
    fun `update memo encodes explicit nulls to clear fields`() = runTest {
        var captured: ApiRequest? = null
        val api = MosaicApi(FakeTransport(rule({ true }) { req ->
            captured = req
            response(200, MEMO_JSON)
        }))
        api.updateMemo(
            "uuid-1",
            buildJsonObject {
                put("diaryDate", kotlinx.serialization.json.JsonNull)
                put("content", JsonPrimitive("更新后的内容"))
            },
        )
        val body = captured!!.bodyUtf8()!!
        assertTrue(body.contains("\"diaryDate\":null"))
        assertTrue(body.contains("\"content\":\"更新后的内容\""))
    }
}

// ----------------------------------------------------------------- auth ----

class AuthedTransportTest {

    @Test
    fun `401 triggers refresh and retries original request`() = runTest {
        val tokenStore = MemoryTokenStore(AuthTokens("expired-token", "refresh-1"))
        val api = MosaicApi(
            AuthedTransport(
                FakeTransport(
                    rule({ it.path == "/api/auth/refresh" }) {
                        response(200, """{"accessToken":"fresh-token","refreshToken":"refresh-2"}""")
                    },
                    rule({ it.path == "/api/auth/me" }) { req ->
                        if (req.headers["Authorization"] == "Bearer fresh-token") {
                            response(200, """{"id":"u1","username":"admin"}""")
                        } else {
                            response(401, """{"error":"401 Unauthorized","message":"Invalid token"}""")
                        }
                    },
                ),
                tokenStore,
            ),
        )

        val user = api.me()

        assertEquals("admin", user.username)
        assertEquals("fresh-token", tokenStore.tokensValue?.accessToken)
        assertEquals("refresh-2", tokenStore.tokensValue?.refreshToken)
    }

    @Test
    fun `failed refresh clears session and throws AuthException`() = runTest {
        val tokenStore = MemoryTokenStore(AuthTokens("expired-token", "dead-refresh"))
        val api = MosaicApi(
            AuthedTransport(
                FakeTransport(
                    rule({ it.path == "/api/auth/me" }) { response(401, """{"error":"401 Unauthorized","message":"Invalid token"}""") },
                    rule({ it.path == "/api/auth/refresh" }) { response(401, """{"error":"401 Unauthorized","message":"Invalid refresh token"}""") },
                ),
                tokenStore,
            ),
        )

        val e = runCatching { api.me() }.exceptionOrNull()

        assertTrue(e is AuthException)
        assertNull(tokenStore.tokensValue)
        assertEquals(1, tokenStore.cleared)
    }

    @Test
    fun `auth endpoints are never retried or decorated`() = runTest {
        val tokenStore = MemoryTokenStore(AuthTokens("t", "r"))
        val requests = mutableListOf<ApiRequest>()
        val api = MosaicApi(
            AuthedTransport(
                object : xyz.cyncyn.mosaic.data.net.HttpTransport {
                    override suspend fun execute(request: ApiRequest): xyz.cyncyn.mosaic.data.net.ApiResponse {
                        requests.add(request)
                        if (request.path == "/api/auth/login") {
                            return response(200, LOGIN_JSON)
                        }
                        return response(401)
                    }
                },
                tokenStore,
            ),
        )

        val login = api.login("admin", "admin123")

        assertEquals("access-abc", login.accessToken)
        val loginRequest = requests.single()
        assertNull(loginRequest.headers["Authorization"])
    }
}

// ---------------------------------------------------------------- storage --

class FileLocalStoreTest {

    @Test
    fun `cache survives across store instances like a process restart`() = runTest {
        val dir = java.nio.file.Files.createTempDirectory("mosaic-cache").toFile()
        val resource = ResourceResponse(
            id = "res-1",
            filename = "sunset.png",
            resourceType = "image",
            mimeType = "image/png",
            url = "/api/resources/res-1/download",
            createdAt = 42L,
        )
        val first = xyz.cyncyn.mosaic.data.store.FileLocalStore(dir)
        first.upsertMemos(listOf(MemoWithResources(id = "m1", content = "跨进程存活的 memo", createdAt = 1, updatedAt = 1)))
        first.upsertDiaries(listOf(DiaryResponse(date = "2026-09-21", summary = "跨进程存活的日记", moodKey = "calm", moodScore = 72)))
        first.upsertResources(listOf(resource))
        first.updateCursors(SyncCursors(memo = 99L))

        // "new process": fresh instance over the same directory
        val second = xyz.cyncyn.mosaic.data.store.FileLocalStore(dir)

        assertEquals("跨进程存活的 memo", second.allMemos().single().content)
        assertEquals("跨进程存活的日记", second.getDiary("2026-09-21")!!.summary)
        assertEquals("sunset.png", second.allResources().single().filename)
        assertEquals(99L, second.getCursors().memo)
        dir.deleteRecursively()
    }
}
