package xyz.cyncyn.mosaic.data.model

import kotlinx.serialization.Serializable

/** All DTOs follow docs/server-api.md v2.6: camelCase fields, ms timestamps. */

@Serializable
data class UserResponse(
    val id: String,
    val username: String,
    val avatarUrl: String? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

@Serializable
data class AuthTokens(
    val accessToken: String,
    val refreshToken: String,
)

@Serializable
data class LoginResponse(
    val accessToken: String,
    val refreshToken: String,
    val user: UserResponse? = null,
)

@Serializable
data class RefreshResponse(
    val accessToken: String,
    val refreshToken: String,
)

@Serializable
data class HealthResponse(
    val status: String = "",
    val version: String = "",
)

@Serializable
data class ResourceResponse(
    val id: String,
    val memoId: String? = null,
    val filename: String = "",
    val resourceType: String = "image",
    val mimeType: String = "application/octet-stream",
    val fileSize: Long = 0,
    val storageType: String = "local",
    val url: String = "",
    val thumbnailUrl: String? = null,
    val metadata: kotlinx.serialization.json.JsonObject? = null,
    val createdAt: Long = 0,
    val updatedAt: Long? = null,
)

@Serializable
data class MemoWithResources(
    val id: String,
    val content: String,
    val tags: List<String> = emptyList(),
    val isArchived: Boolean = false,
    val diaryDate: String? = null,
    val aiSummary: String? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val revisionCount: Int = 0,
    val resources: List<ResourceResponse> = emptyList(),
    // present only in search results (contract §7.10)
    val semanticScore: Double? = null,
    val keywordScore: Double? = null,
    val matchType: String? = null,
)

@Serializable
data class MemoRevision(
    val id: String,
    val memoId: String,
    val revisionNumber: Int = 1,
    val content: String,
    val tags: List<String> = emptyList(),
    val aiSummary: String? = null,
    val createdAt: Long = 0,
)

@Serializable
data class BotSummary(
    val id: String,
    val name: String,
    val avatarUrl: String? = null,
)

@Serializable
data class BotReply(
    val id: String,
    val memoId: String,
    val bot: BotSummary? = null,
    val content: String = "",
    val thinkingContent: String? = null,
    val parentReplyId: String? = null,
    val userQuestion: String? = null,
    val revisionNumber: Int? = null,
    val createdAt: Long = 0,
    val children: List<BotReply> = emptyList(),
    val threadCount: Int = 0,
    val latestReplyId: String? = null,
)

@Serializable
data class MemoDetail(
    val memo: MemoWithResources,
    val revisions: List<MemoRevision> = emptyList(),
    val botReplies: List<BotReply> = emptyList(),
)

@Serializable
data class DiaryResponse(
    val date: String,
    val summary: String = "",
    val moodKey: String = "neutral",
    val moodScore: Int = 50,
    val generationSource: String = "manual",
    val autoGenerationLocked: Boolean = false,
    val generatedFromMemoIds: List<String> = emptyList(),
    val lastAutoGeneratedAt: Long? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

@Serializable
data class DiaryWithMemos(
    val date: String,
    val summary: String = "",
    val moodKey: String = "neutral",
    val moodScore: Int = 50,
    val generationSource: String = "manual",
    val autoGenerationLocked: Boolean = false,
    val generatedFromMemoIds: List<String> = emptyList(),
    val lastAutoGeneratedAt: Long? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val memos: List<MemoWithResources> = emptyList(),
)

@Serializable
data class BotMemoryStats(
    val totalContextsBuilt: Int = 0,
    val lastContextAt: Long? = null,
)

@Serializable
data class BotResponse(
    val id: String,
    val name: String,
    val avatarUrl: String? = null,
    val description: String = "",
    val tags: List<String> = emptyList(),
    val autoReply: Boolean = true,
    val sortOrder: Int = 0,
    val model: String? = null,
    val aiConfig: kotlinx.serialization.json.JsonObject? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val memoryStats: BotMemoryStats? = null,
)

@Serializable
data class TagCount(
    val tag: String,
    val count: Int = 0,
)

@Serializable
data class SearchMemosResponse(
    val memos: List<MemoWithResources> = emptyList(),
    val total: Int = 0,
    val page: Int = 1,
    val pageSize: Int = 50,
    val semanticEnabled: Boolean = false,
)

@Serializable
data class HeatmapResponse(
    val dates: List<String> = emptyList(),
    val counts: List<Int> = emptyList(),
    val moods: List<String?> = emptyList(),
    val moodScores: List<Int?> = emptyList(),
)

@Serializable
data class SyncCursors(
    val memo: Long? = null,
    val diary: Long? = null,
    val resource: Long? = null,
    val bot: Long? = null,
) {
    companion object {
        val EMPTY = SyncCursors()
    }
}

@Serializable
data class EntityChanges<T>(
    val updated: List<T> = emptyList(),
    val deletedIds: List<String> = emptyList(),
) {
    val changeCount: Int get() = updated.size + deletedIds.size
}

@Serializable
data class SyncEntityChanges(
    val memo: EntityChanges<MemoWithResources> = EntityChanges(),
    val diary: EntityChanges<DiaryResponse> = EntityChanges(),
    val resource: EntityChanges<ResourceResponse> = EntityChanges(),
    val bot: EntityChanges<BotResponse> = EntityChanges(),
) {
    val totalChanges: Int get() = memo.changeCount + diary.changeCount + resource.changeCount + bot.changeCount
}

@Serializable
data class SyncPullResponse(
    val cursors: SyncCursors = SyncCursors(),
    val changes: SyncEntityChanges = SyncEntityChanges(),
)

@Serializable
data class SyncResult(
    val pulled: Int,
    val cursors: SyncCursors,
    val rounds: Int,
)

@Serializable
data class PaginatedResponse<T>(
    val items: List<T> = emptyList(),
    val total: Int = 0,
    val page: Int = 1,
    val pageSize: Int = 20,
    val totalPages: Int = 1,
)
