package service

import (
	"context"
	"errors"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"github.com/crayonlu/mosaic/server-go/internal/domain"
	"github.com/crayonlu/mosaic/server-go/internal/retry"
)

// --- fakes -----------------------------------------------------------------

type fakeAIDiarySettings struct{ values map[string]string }

func (f fakeAIDiarySettings) Bool(_ context.Context, key string, fallback bool) bool {
	switch f.values[key] {
	case "true":
		return true
	case "false":
		return false
	default:
		return fallback
	}
}

func (f fakeAIDiarySettings) Int(_ context.Context, key string, fallback int32) int32 {
	parsed, err := strconv.Atoi(f.values[key])
	if err != nil {
		return fallback
	}
	return int32(parsed)
}

type fakeAIDiaryTimezone struct{ loc *time.Location }

func (f fakeAIDiaryTimezone) Timezone(context.Context) *time.Location { return f.loc }

type fakeAIDiaryConfigs struct {
	config domain.AIConfig
	err    error
}

func (f fakeAIDiaryConfigs) ChatConfig(context.Context, uuid.UUID) (domain.AIConfig, error) {
	return f.config, f.err
}

type fakeAIDiaryChat struct {
	reply    string
	err      error
	calls    int
	requests []AIDiaryCompletionRequest
}

func (f *fakeAIDiaryChat) Complete(_ context.Context, req AIDiaryCompletionRequest) (string, error) {
	f.calls++
	f.requests = append(f.requests, req)
	if f.err != nil {
		return "", f.err
	}
	return f.reply, nil
}

type fakeEnqueuedJob struct {
	userID   uuid.UUID
	date     domain.Date
	runAfter int64
	now      int64
}

type fakeSavedDiary struct {
	userID    uuid.UUID
	date      domain.Date
	summary   string
	moodKey   string
	moodScore int32
	memoIDs   []uuid.UUID
	now       int64
}

type fakeFailedJob struct {
	job       AIDiaryJob
	lastError string
	runAfter  int64
}

type fakeAIDiaryStore struct {
	due       []AIDiaryJob
	diaries   map[string]domain.Diary
	memos     []domain.Memo
	enqueued  []fakeEnqueuedJob
	saved     []fakeSavedDiary
	completed []AIDiaryJob
	failed    []fakeFailedJob
}

func newFakeAIDiaryStore() *fakeAIDiaryStore {
	return &fakeAIDiaryStore{diaries: map[string]domain.Diary{}}
}

func fakeJobKey(userID uuid.UUID, date domain.Date) string {
	return userID.String() + "|" + date.String()
}

func (f *fakeAIDiaryStore) EnqueueJob(
	_ context.Context, userID uuid.UUID, targetDate domain.Date, runAfterMS, now int64,
) error {
	f.enqueued = append(f.enqueued, fakeEnqueuedJob{userID, targetDate, runAfterMS, now})
	return nil
}

func (f *fakeAIDiaryStore) ClaimDueJobs(context.Context, int64, int) ([]AIDiaryJob, error) {
	claimed := f.due
	f.due = nil
	return claimed, nil
}

func (f *fakeAIDiaryStore) CompleteJob(
	_ context.Context, userID uuid.UUID, targetDate domain.Date, _ int64,
) error {
	f.completed = append(f.completed, AIDiaryJob{UserID: userID, TargetDate: targetDate})
	return nil
}

func (f *fakeAIDiaryStore) FailJob(
	_ context.Context, userID uuid.UUID, targetDate domain.Date, lastError string, runAfterMS, _ int64,
) error {
	f.failed = append(f.failed, fakeFailedJob{
		job:       AIDiaryJob{UserID: userID, TargetDate: targetDate},
		lastError: lastError, runAfter: runAfterMS,
	})
	return nil
}

func (f *fakeAIDiaryStore) DiaryForDate(
	_ context.Context, userID uuid.UUID, targetDate domain.Date,
) (domain.Diary, error) {
	diary, ok := f.diaries[fakeJobKey(userID, targetDate)]
	if !ok {
		return domain.Diary{}, domain.ErrNoRows
	}
	return diary, nil
}

func (f *fakeAIDiaryStore) CandidateMemos(
	context.Context, uuid.UUID, int64, int64,
) ([]domain.Memo, error) {
	return f.memos, nil
}

// SaveGeneratedDiary models the real store's guarded upsert: a locked diary is
// never overwritten and a successful write is tagged as auto-generated.
func (f *fakeAIDiaryStore) SaveGeneratedDiary(
	_ context.Context, userID uuid.UUID, targetDate domain.Date,
	summary, moodKey string, moodScore int32, memoIDs []uuid.UUID, now int64,
) error {
	f.saved = append(f.saved, fakeSavedDiary{
		userID: userID, date: targetDate, summary: summary, moodKey: moodKey,
		moodScore: moodScore, memoIDs: memoIDs, now: now,
	})
	key := fakeJobKey(userID, targetDate)
	if existing, ok := f.diaries[key]; ok && existing.AutoGenerationLocked {
		return nil
	}
	f.diaries[key] = domain.Diary{
		Date: targetDate, UserID: userID, Summary: summary, MoodKey: moodKey,
		MoodScore: moodScore, GenerationSource: domain.GenerationSourceAI,
		GeneratedFromMemoIDs: memoIDs, LastAutoGeneratedAt: &now, CreatedAt: now, UpdatedAt: now,
	}
	return nil
}

// --- helpers ---------------------------------------------------------------

var testLoc = time.FixedZone("CST", 8*60*60)

func testDate(y int, m time.Month, d int) domain.Date {
	return domain.NewDate(time.Date(y, m, d, 0, 0, 0, 0, testLoc))
}

func dayMS(y int, m time.Month, d, hour, minute int) int64 {
	return time.Date(y, m, d, hour, minute, 0, 0, testLoc).UnixMilli()
}

func testMemo(userID uuid.UUID, content string, createdAt int64) domain.Memo {
	return domain.Memo{ID: uuid.New(), UserID: userID, Content: content, CreatedAt: createdAt}
}

// twoLongMemos gives a day enough material to clear the default thresholds.
func twoLongMemos(userID uuid.UUID) []domain.Memo {
	return []domain.Memo{
		testMemo(userID, strings.Repeat("a", 200), dayMS(2026, 5, 1, 9, 0)),
		testMemo(userID, strings.Repeat("b", 200), dayMS(2026, 5, 1, 20, 0)),
	}
}

func fastRetryPolicy() retry.Policy {
	return retry.Policy{
		MaxRetries: 0, Timeout: time.Second,
		Backoff: func(int) time.Duration { return 0 },
		Sleep:   func(context.Context, time.Duration) error { return nil },
	}
}

func newTestService(
	store AIDiaryStore, settings AIDiarySettings, chat AIDiaryChatClient, now int64,
) *AIDiaryService {
	return NewAIDiaryService(
		store, settings, fakeAIDiaryTimezone{loc: testLoc},
		fakeAIDiaryConfigs{config: domain.AIConfig{
			Provider: "openai", BaseURL: "https://example.test", APIKey: "key", Model: "model",
		}},
		chat,
		fakeAIDiaryImages{},
	).WithClock(func() int64 { return now }).WithRetryPolicy(fastRetryPolicy())
}

// --- pure logic ------------------------------------------------------------

func TestComputeRunAfter(t *testing.T) {
	cases := []struct {
		name     string
		loc      *time.Location
		target   domain.Date
		wantDate string
	}{
		{"next day in UTC+8", testLoc, testDate(2026, 5, 1), "2026-05-02T00:05:00+08:00"},
		{"rolls over the month in UTC", time.UTC, domain.NewDate(time.Date(2026, 1, 31, 0, 0, 0, 0, time.UTC)), "2026-02-01T00:05:00Z"},
	}
	for _, tc := range cases {
		got := time.UnixMilli(ComputeRunAfter(tc.target, tc.loc)).In(tc.loc).Format(time.RFC3339)
		if got != tc.wantDate {
			t.Errorf("%s: ComputeRunAfter = %s, want %s", tc.name, got, tc.wantDate)
		}
	}
}

func TestDateFromTimestampAppliesTimezone(t *testing.T) {
	ts := time.Date(2026, 5, 1, 16, 30, 0, 0, time.UTC).UnixMilli()
	if got := DateFromTimestamp(ts, time.UTC).String(); got != "2026-05-01" {
		t.Errorf("UTC date = %q, want 2026-05-01", got)
	}
	if got := DateFromTimestamp(ts, testLoc).String(); got != "2026-05-02" {
		t.Errorf("UTC+8 date = %q, want 2026-05-02 (next day)", got)
	}
}

func TestShouldGenerateDiaryBoundary(t *testing.T) {
	const minMemos, minChars = 2, 150
	cases := []struct {
		name         string
		memos, chars int
		want         bool
	}{
		{"exactly at both thresholds", 2, 150, true},
		{"one char short at min memos", 2, 149, false},
		{"one char over at min memos", 2, 151, true},
		{"extra memo overrides char shortfall", 3, 0, true},
		{"below min memos with plenty of chars", 1, 10000, false},
		{"no content", 0, 0, false},
	}
	for _, tc := range cases {
		if got := ShouldGenerateDiary(tc.memos, tc.chars, minMemos, minChars); got != tc.want {
			t.Errorf("%s: ShouldGenerateDiary(%d, %d) = %v, want %v",
				tc.name, tc.memos, tc.chars, got, tc.want)
		}
	}
}

func TestBuildDiaryMessagesAndSystemPrompt(t *testing.T) {
	target := testDate(2026, 5, 1)
	summary := "worked on the parser"
	memos := []domain.Memo{
		testMemo(uuid.New(), "morning walk", dayMS(2026, 5, 1, 9, 30)),
		{ID: uuid.New(), Content: "fixed a bug", AiSummary: &summary, CreatedAt: dayMS(2026, 5, 1, 18, 5)},
	}

	messages := BuildDiaryMessages(target, memos, testLoc)
	if len(messages) != 3 {
		t.Fatalf("messages = %d, want 3 (preamble + one per memo)", len(messages))
	}
	if !strings.Contains(messages[0].Content, "2026-05-01") {
		t.Errorf("preamble = %q, want it to name the target date", messages[0].Content)
	}
	if !strings.Contains(messages[1].Content, "[09:30] morning walk") {
		t.Errorf("first memo message = %q, want timestamped content", messages[1].Content)
	}
	if !strings.Contains(messages[2].Content, "AI Summary: worked on the parser") {
		t.Errorf("second memo message = %q, want the AI summary appended", messages[2].Content)
	}

	prompt := BuildDiarySystemPrompt()
	for _, key := range allowedMoodKeys {
		if !strings.Contains(prompt, key) {
			t.Errorf("system prompt missing mood key %q", key)
		}
	}
	if !strings.Contains(prompt, "summary, moodKey, moodScore") {
		t.Error("system prompt missing the JSON contract")
	}
}

func TestParseAIDiaryPayloadValidates(t *testing.T) {
	payload, err := ParseAIDiaryPayload(`here: {"summary":"  a day  ","moodKey":"joy","moodScore":9}`)
	if err != nil {
		t.Fatalf("ParseAIDiaryPayload: %v", err)
	}
	if payload.Summary != "a day" || payload.MoodKey != "joy" || payload.MoodScore != 9 {
		t.Errorf("payload = %+v, want trimmed summary and parsed mood", payload)
	}
	for _, raw := range []string{
		"no json here",
		`{"summary":"","moodKey":"joy","moodScore":5}`,
		`{"summary":"x","moodKey":"unknown","moodScore":5}`,
		`{"summary":"x","moodKey":"joy","moodScore":0}`,
		`{"summary":"x","moodKey":"joy","moodScore":11}`,
	} {
		if _, err := ParseAIDiaryPayload(raw); err == nil {
			t.Errorf("ParseAIDiaryPayload(%q) succeeded, want an error", raw)
		}
	}
}

// --- service behaviour -----------------------------------------------------

func TestProcessDueJobsBelowThresholdCompletesWithoutDiary(t *testing.T) {
	now := dayMS(2026, 5, 2, 0, 10)
	userID := uuid.New()
	job := AIDiaryJob{UserID: userID, TargetDate: testDate(2026, 5, 1)}

	store := newFakeAIDiaryStore()
	store.due = []AIDiaryJob{job}
	store.memos = []domain.Memo{testMemo(userID, "too short", dayMS(2026, 5, 1, 12, 0))}
	chat := &fakeAIDiaryChat{reply: `{"summary":"x","moodKey":"calm","moodScore":5}`}

	processed, err := newTestService(store, fakeAIDiarySettings{}, chat, now).
		ProcessDueJobs(context.Background())
	if err != nil {
		t.Fatalf("ProcessDueJobs: %v", err)
	}
	if processed != 1 {
		t.Errorf("processed = %d, want 1", processed)
	}
	if len(store.saved) != 0 || chat.calls != 0 {
		t.Errorf("saved=%d chatCalls=%d, want 0 below the threshold", len(store.saved), chat.calls)
	}
	if len(store.failed) != 0 {
		t.Errorf("failed jobs = %d, want 0 (a skip is not a failure)", len(store.failed))
	}
	if len(store.completed) != 1 || store.completed[0] != job {
		t.Errorf("completed = %+v, want [%+v]", store.completed, job)
	}
}

func TestProcessDueJobsGeneratesAutoDiary(t *testing.T) {
	now := dayMS(2026, 5, 2, 0, 10)
	userID := uuid.New()
	target := testDate(2026, 5, 1)
	job := AIDiaryJob{UserID: userID, TargetDate: target}

	store := newFakeAIDiaryStore()
	store.due = []AIDiaryJob{job}
	store.memos = twoLongMemos(userID)
	chat := &fakeAIDiaryChat{reply: `{"summary":"a reflective day","moodKey":"calm","moodScore":7}`}

	if _, err := newTestService(store, fakeAIDiarySettings{}, chat, now).
		ProcessDueJobs(context.Background()); err != nil {
		t.Fatalf("ProcessDueJobs: %v", err)
	}
	if len(store.saved) != 1 || chat.calls != 1 {
		t.Fatalf("saved=%d chatCalls=%d, want 1 each", len(store.saved), chat.calls)
	}
	if len(chat.requests[0].Messages) != 3 {
		t.Errorf("prompt messages = %d, want 3 (preamble + 2 memos)", len(chat.requests[0].Messages))
	}

	diary, err := store.DiaryForDate(context.Background(), userID, target)
	if err != nil {
		t.Fatalf("DiaryForDate: %v", err)
	}
	if diary.GenerationSource != domain.GenerationSourceAI {
		t.Errorf("generation source = %q, want %q", diary.GenerationSource, domain.GenerationSourceAI)
	}
	if diary.AutoGenerationLocked {
		t.Error("auto-generated diary is locked, want unlocked")
	}
	if diary.LastAutoGeneratedAt == nil || *diary.LastAutoGeneratedAt != now {
		t.Errorf("last auto generated at = %v, want %d", diary.LastAutoGeneratedAt, now)
	}
	if len(diary.GeneratedFromMemoIDs) != 2 {
		t.Errorf("generated from %d memos, want 2", len(diary.GeneratedFromMemoIDs))
	}
	if len(store.failed) != 0 || len(store.completed) != 1 {
		t.Errorf("failed=%d completed=%d, want 0 and 1", len(store.failed), len(store.completed))
	}
}

func TestProcessDueJobsDoesNotOverwriteLockedDiary(t *testing.T) {
	now := dayMS(2026, 5, 2, 0, 10)
	userID := uuid.New()
	target := testDate(2026, 5, 1)
	job := AIDiaryJob{UserID: userID, TargetDate: target}

	store := newFakeAIDiaryStore()
	store.due = []AIDiaryJob{job}
	store.memos = twoLongMemos(userID)
	store.diaries[fakeJobKey(userID, target)] = domain.Diary{
		Date: target, UserID: userID, Summary: "hand written",
		GenerationSource: domain.GenerationSourceManual, AutoGenerationLocked: true,
	}
	chat := &fakeAIDiaryChat{reply: `{"summary":"should not land","moodKey":"calm","moodScore":7}`}

	if _, err := newTestService(store, fakeAIDiarySettings{}, chat, now).
		ProcessDueJobs(context.Background()); err != nil {
		t.Fatalf("ProcessDueJobs: %v", err)
	}
	if chat.calls != 0 || len(store.saved) != 0 {
		t.Errorf("chatCalls=%d saved=%d, want 0 for a locked diary", chat.calls, len(store.saved))
	}
	diary, err := store.DiaryForDate(context.Background(), userID, target)
	if err != nil {
		t.Fatalf("DiaryForDate: %v", err)
	}
	if diary.Summary != "hand written" || !diary.AutoGenerationLocked {
		t.Errorf("locked diary = %+v, want it untouched", diary)
	}
}

func TestProcessDueJobsProviderFailureLeavesJobRetryable(t *testing.T) {
	now := dayMS(2026, 5, 2, 0, 10)
	userID := uuid.New()
	target := testDate(2026, 5, 1)
	job := AIDiaryJob{UserID: userID, TargetDate: target}

	store := newFakeAIDiaryStore()
	store.due = []AIDiaryJob{job}
	store.memos = twoLongMemos(userID)
	chat := &fakeAIDiaryChat{err: errors.New("provider exploded")}

	// A per-job failure must not fail the sweep.
	if _, err := newTestService(store, fakeAIDiarySettings{}, chat, now).
		ProcessDueJobs(context.Background()); err != nil {
		t.Fatalf("ProcessDueJobs should not fail on a per-job error: %v", err)
	}
	if len(store.saved) != 0 || len(store.completed) != 0 {
		t.Errorf("saved=%d completed=%d, want 0 after a provider failure",
			len(store.saved), len(store.completed))
	}
	if len(store.failed) != 1 {
		t.Fatalf("failed jobs = %d, want 1", len(store.failed))
	}
	failed := store.failed[0]
	if failed.job != job {
		t.Errorf("failed job = %+v, want %+v", failed.job, job)
	}
	if !strings.Contains(failed.lastError, "provider exploded") {
		t.Errorf("last error = %q, want it to carry the provider failure", failed.lastError)
	}
	if want := now + aiDiaryRetryDelayMS; failed.runAfter != want {
		t.Errorf("retry run after = %d, want %d", failed.runAfter, want)
	}
}

func TestQueueJobForMemoUsesMemoDayAndNextDayRunTime(t *testing.T) {
	now := dayMS(2026, 5, 1, 23, 0)
	userID := uuid.New()
	memo := testMemo(userID, "late night thought", now)

	store := newFakeAIDiaryStore()
	if err := newTestService(store, fakeAIDiarySettings{}, &fakeAIDiaryChat{}, now).
		QueueJobForMemo(context.Background(), memo); err != nil {
		t.Fatalf("QueueJobForMemo: %v", err)
	}
	if len(store.enqueued) != 1 {
		t.Fatalf("enqueued jobs = %d, want 1", len(store.enqueued))
	}
	enqueued := store.enqueued[0]
	if enqueued.userID != userID || enqueued.date.String() != "2026-05-01" {
		t.Errorf("enqueued = %+v, want user %s on 2026-05-01", enqueued, userID)
	}
	if want := ComputeRunAfter(enqueued.date, testLoc); enqueued.runAfter != want {
		t.Errorf("run after = %d, want %d", enqueued.runAfter, want)
	}
	if enqueued.now != now {
		t.Errorf("enqueued now = %d, want %d", enqueued.now, now)
	}
}

// fakeAIDiaryImages serves a memo's images from memory.
type fakeAIDiaryImages struct {
	images map[uuid.UUID][]ImageInput
	err    error
}

func (f fakeAIDiaryImages) MemoImages(
	_ context.Context, _ uuid.UUID, memoID uuid.UUID, _ int,
) ([]ImageInput, error) {
	if f.err != nil {
		return nil, f.err
	}
	return f.images[memoID], nil
}
