package httpapi

import (
	"github.com/crayonlu/mosaic/server-go/internal/domain"
	"github.com/crayonlu/mosaic/server-go/internal/service"
)

// Request and response bodies for the diary endpoints. Field names are part of
// the wire contract with installed clients.

type createDiaryRequest struct {
	// Date is accepted for compatibility but the path segment always wins.
	Date      string `json:"date"`
	Summary   string `json:"summary"`
	MoodKey   string `json:"moodKey"`
	MoodScore int32  `json:"moodScore"`
}

type updateDiaryRequest struct {
	Summary   *string `json:"summary"`
	MoodKey   *string `json:"moodKey"`
	MoodScore *int32  `json:"moodScore"`
}

type updateDiarySummaryRequest struct {
	Summary string `json:"summary"`
}

type updateDiaryMoodRequest struct {
	MoodKey   string `json:"moodKey"`
	MoodScore int32  `json:"moodScore"`
}

type diaryResponse struct {
	Date                 string   `json:"date"`
	Summary              string   `json:"summary"`
	MoodKey              string   `json:"moodKey"`
	MoodScore            int32    `json:"moodScore"`
	GenerationSource     string   `json:"generationSource"`
	AutoGenerationLocked bool     `json:"autoGenerationLocked"`
	GeneratedFromMemoIDs []string `json:"generatedFromMemoIds"`
	LastAutoGeneratedAt  *int64   `json:"lastAutoGeneratedAt"`
	CreatedAt            int64    `json:"createdAt"`
	UpdatedAt            int64    `json:"updatedAt"`
}

type diaryResourceResponse struct {
	ID            string         `json:"id"`
	MemoID        *string        `json:"memoId"`
	Filename      string         `json:"filename"`
	ResourceType  string         `json:"resourceType"`
	MimeType      string         `json:"mimeType"`
	Size          int64          `json:"size"`
	StorageType   *string        `json:"storageType"`
	StoragePath   *string        `json:"storagePath"`
	URL           string         `json:"url"`
	ThumbnailURL  *string        `json:"thumbnailUrl"`
	Metadata      map[string]any `json:"metadata"`
	AIDescription *string        `json:"aiDescription"`
	CreatedAt     int64          `json:"createdAt"`
}

type diaryMemoResponse struct {
	ID            string                  `json:"id"`
	Content       string                  `json:"content"`
	Tags          []string                `json:"tags"`
	IsArchived    bool                    `json:"isArchived"`
	DiaryDate     *string                 `json:"diaryDate"`
	AISummary     *string                 `json:"aiSummary"`
	CreatedAt     int64                   `json:"createdAt"`
	UpdatedAt     int64                   `json:"updatedAt"`
	RevisionCount int32                   `json:"revisionCount"`
	Resources     []diaryResourceResponse `json:"resources"`
}

// diaryWithMemosResponse flattens the diary fields and appends the day's memos.
type diaryWithMemosResponse struct {
	diaryResponse
	Memos []diaryMemoResponse `json:"memos"`
}

func toDiaryResponse(diary domain.Diary) diaryResponse {
	memoIDs := make([]string, 0, len(diary.GeneratedFromMemoIDs))
	for _, id := range diary.GeneratedFromMemoIDs {
		memoIDs = append(memoIDs, id.String())
	}

	return diaryResponse{
		Date:                 diary.Date.String(),
		Summary:              diary.Summary,
		MoodKey:              diary.MoodKey,
		MoodScore:            diary.MoodScore,
		GenerationSource:     diary.GenerationSource,
		AutoGenerationLocked: diary.AutoGenerationLocked,
		GeneratedFromMemoIDs: memoIDs,
		LastAutoGeneratedAt:  diary.LastAutoGeneratedAt,
		CreatedAt:            diary.CreatedAt,
		UpdatedAt:            diary.UpdatedAt,
	}
}

func toPaginatedDiaryResponse(page domain.Paginated[domain.Diary]) domain.Paginated[diaryResponse] {
	items := make([]diaryResponse, 0, len(page.Items))
	for _, diary := range page.Items {
		items = append(items, toDiaryResponse(diary))
	}
	return domain.Paginated[diaryResponse]{
		Items:      items,
		Total:      page.Total,
		Page:       page.Page,
		PageSize:   page.PageSize,
		TotalPages: page.TotalPages,
	}
}

func toDiaryWithMemosResponse(detail service.DiaryDetail) diaryWithMemosResponse {
	memos := make([]diaryMemoResponse, 0, len(detail.Memos))
	for _, memo := range detail.Memos {
		resources := make([]diaryResourceResponse, 0, len(memo.Resources))
		for _, resource := range memo.Resources {
			resources = append(resources, toDiaryResourceResponse(resource))
		}
		memos = append(memos, diaryMemoResponse{
			ID:            memo.Memo.ID.String(),
			Content:       memo.Memo.Content,
			Tags:          diaryStringList(memo.Memo.Tags),
			IsArchived:    memo.Memo.IsArchived,
			DiaryDate:     domain.StringOrNil(memo.Memo.DiaryDate),
			AISummary:     memo.Memo.AiSummary,
			CreatedAt:     memo.Memo.CreatedAt,
			UpdatedAt:     memo.Memo.UpdatedAt,
			RevisionCount: memo.Memo.RevisionCount,
			Resources:     resources,
		})
	}

	return diaryWithMemosResponse{
		diaryResponse: toDiaryResponse(detail.Diary),
		Memos:         memos,
	}
}

func toDiaryResourceResponse(resource domain.Resource) diaryResourceResponse {
	storageType := resource.StorageType
	storagePath := resource.StoragePath
	metadata := resource.Metadata
	if metadata == nil {
		metadata = map[string]any{}
	}

	var memoID *string
	if resource.MemoID != nil {
		rendered := resource.MemoID.String()
		memoID = &rendered
	}

	var thumbnailURL *string
	if diaryVideoMimeType(resource.MimeType) {
		route := domain.ThumbnailRoute(resource.ID)
		thumbnailURL = &route
	}

	return diaryResourceResponse{
		ID:            resource.ID.String(),
		MemoID:        memoID,
		Filename:      resource.Filename,
		ResourceType:  resource.Type,
		MimeType:      resource.MimeType,
		Size:          resource.FileSize,
		StorageType:   &storageType,
		StoragePath:   &storagePath,
		URL:           domain.DownloadRoute(resource.ID),
		ThumbnailURL:  thumbnailURL,
		Metadata:      metadata,
		AIDescription: resource.AiDescription,
		CreatedAt:     resource.CreatedAt,
	}
}

func diaryVideoMimeType(mimeType string) bool {
	return len(mimeType) >= len("video/") && mimeType[:len("video/")] == "video/"
}

// diaryStringList keeps list fields as [] rather than null on the wire.
func diaryStringList(values []string) []string {
	if values == nil {
		return []string{}
	}
	return values
}
