package domain

import "github.com/google/uuid"

// Generation sources recorded on a diary entry. The values are wire contract:
// clients and the sync payload already use them.
const (
	GenerationSourceManual = "manual"
	GenerationSourceAI     = "ai"
)

// Diary is one day's summary and mood.
type Diary struct {
	Date                 Date
	UserID               uuid.UUID
	Summary              string
	MoodKey              string
	MoodScore            int32
	GenerationSource     string
	AutoGenerationLocked bool
	GeneratedFromMemoIDs []uuid.UUID
	LastAutoGeneratedAt  *int64
	CreatedAt            int64
	UpdatedAt            int64
	IsDeleted            bool
}

// DiaryFilter are the filters the list endpoint accepts.
type DiaryFilter struct {
	Page      uint32
	PageSize  uint32
	StartDate *Date
	EndDate   *Date
}

// DiaryWithMemos is a diary entry together with that day's memos.
type DiaryWithMemos struct {
	Diary Diary
	Memos []Memo
}
