#!/usr/bin/env node
/**
 * Mosaic contract stub server — implements docs/server-api.md (v2.6).
 *
 * Zero-dependency Node ESM. Doubles as:
 *  1. test backend for the Android app (emulator reaches it via 10.0.2.2:<port>)
 *  2. request recorder: every request is appended to --log file
 *
 * Usage:
 *   node server.mjs [--port 8080] [--log /path/requests.log]
 *
 * Test-only hooks (not part of the contract):
 *   POST /__stub/reset   — restore seed data
 *   POST /__stub/inject  — body {content, tags?} adds a memo at runtime
 */
import http from 'node:http'
import fs from 'node:fs'
import crypto from 'node:crypto'

const args = process.argv.slice(2)
function argOf(name, fallback) {
  const i = args.indexOf(name)
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback
}
const PORT = Number(argOf('--port', process.env.STUB_PORT || 8080))
const LOG_PATH = argOf('--log', process.env.STUB_REQUEST_LOG || null)

// ---------------------------------------------------------------- seeds ----

const NOW = Date.now()
const T = (h) => NOW - h * 3600_000 // hours ago, relative to device/server now
const dayStr = (offsetDays) => {
  const d = new Date(NOW - offsetDays * 86400_000)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}
const png1x1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
  'base64',
)

let db
function seed() {
  db = {
    user: {
      id: 'seed-user-0001',
      username: process.env.STUB_USERNAME || 'admin',
      avatarUrl: null,
      createdAt: T(0),
      updatedAt: T(0),
    },
    password: process.env.STUB_PASSWORD || 'admin123',
    accessTokens: new Map(), // token -> { userId, authed: true }
    refreshTokens: new Map(), // token -> userId
    memos: [
      {
        id: 'memo-0001',
        content: '把 design-core 的三层 token 接到了真实数据层，同步游标第一次跑通',
        tags: ['设计系统', '迁移'],
        isArchived: false,
        diaryDate: null,
        aiSummary: null,
        createdAt: T(8),
        updatedAt: T(8),
        revisionCount: 2,
        resourceIds: [],
      },
      {
        id: 'memo-0002',
        content: '晨跑五公里，状态很好',
        tags: ['运动'],
        isArchived: false,
        diaryDate: null,
        aiSummary: null,
        createdAt: T(26),
        updatedAt: T(26),
        revisionCount: 1,
        resourceIds: [],
      },
      {
        id: 'memo-0003',
        content: '读完《卡片笔记写作法》第三章，永久笔记要用自己的话重写',
        tags: ['读书'],
        isArchived: false,
        diaryDate: dayStr(1),
        aiSummary: '永久笔记的核心是转述而非摘抄',
        createdAt: T(5),
        updatedAt: T(5),
        revisionCount: 1,
        resourceIds: ['res-0001'],
      },
      {
        id: 'memo-0004',
        content: '和设计师对了首页的留白节奏，纸面感更强了',
        tags: ['设计'],
        isArchived: true,
        diaryDate: null,
        aiSummary: null,
        createdAt: T(50),
        updatedAt: T(50),
        revisionCount: 1,
        resourceIds: [],
      },
      {
        id: 'memo-0005',
        content: [
          '# 同步引擎笔记',
          '',
          '游标按 `updatedAt` 推进，拉取分页上限 200 条。',
          '',
          '- 拉取 → 应用变更 → 推进游标',
          '- 再次拉取直到增量清空',
          '',
          '> 离线优先：先渲染缓存，再等网络。',
          '',
          '```kotlin',
          'fun sync(cursors: Cursors): SyncResult {',
          '  val pull = api.pull(cursors)',
          '  store.apply(pull.changes)',
          '  return pull.toResult()',
          '}',
          '```',
        ].join('\n'),
        tags: ['技术'],
        isArchived: false,
        diaryDate: dayStr(1),
        aiSummary: null,
        createdAt: T(28),
        updatedAt: T(28),
        revisionCount: 1,
        resourceIds: [],
      },
      {
        id: 'memo-0006',
        content: '给同步引擎补了离线渲染的测试夹具',
        tags: ['技术', '同步'],
        isArchived: false,
        diaryDate: null,
        aiSummary: null,
        createdAt: T(3),
        updatedAt: T(3),
        revisionCount: 1,
        resourceIds: [],
      },
    ],
    diaries: [
      {
        date: dayStr(0),
        summary: '状态平稳，完成了重写计划的第一阶段',
        moodKey: 'calm',
        moodScore: 72,
        generationSource: 'manual',
        autoGenerationLocked: false,
        generatedFromMemoIds: [],
        lastAutoGeneratedAt: null,
        createdAt: T(5),
        updatedAt: T(5),
      },
      {
        date: dayStr(1),
        summary: '写完了 markdown 渲染器的骨架',
        moodKey: 'focus',
        moodScore: 80,
        generationSource: 'manual',
        autoGenerationLocked: false,
        generatedFromMemoIds: [],
        lastAutoGeneratedAt: null,
        createdAt: T(29),
        updatedAt: T(29),
      },
      {
        date: dayStr(2),
        summary: '晨跑加阅读，充实的一天',
        moodKey: 'joy',
        moodScore: 85,
        generationSource: 'manual',
        autoGenerationLocked: false,
        generatedFromMemoIds: [],
        lastAutoGeneratedAt: null,
        createdAt: T(53),
        updatedAt: T(53),
      },
    ],
    resources: [
      {
        id: 'res-0001',
        memoId: 'memo-0003',
        filename: 'sunset.png',
        resourceType: 'image',
        mimeType: 'image/png',
        fileSize: png1x1.length,
        storageType: 'local',
        url: '/api/resources/res-0001/download',
        thumbnailUrl: '/api/resources/res-0001/thumbnail',
        updatedAt: T(1),
        metadata: { width: 1, height: 1 },
        createdAt: T(8),
      },
    ],
    bots: [
      {
        id: 'bot-0001',
        name: '墨墨助手',
        avatarUrl: null,
        description: '安静地陪着你记录',
        tags: ['助手'],
        autoReply: true,
        sortOrder: 0,
        model: null,
        aiConfig: null,
        createdAt: T(8),
        updatedAt: T(8),
        memoryStats: { totalContextsBuilt: 2, lastContextAt: T(6) },
      },
    ],
    botReplies: [
      {
        id: 'reply-0001',
        memoId: 'memo-0001',
        bot: { id: 'bot-0001', name: '墨墨助手', avatarUrl: null },
        content: '已经把这条 memo 记入长期记忆了。',
        thinkingContent: null,
        parentReplyId: null,
        userQuestion: null,
        revisionNumber: null,
        createdAt: T(2),
        children: [],
        threadCount: 0,
        latestReplyId: 'reply-0001',
      },
    ],
    revisions: [
      {
        id: 'rev-0001',
        memoId: 'memo-0001',
        revisionNumber: 1,
        content: '把 design-core 的三层 token 接到了缓存层',
        tags: ['设计系统'],
        aiSummary: null,
        createdAt: T(8),
      },
      {
        id: 'rev-0002',
        memoId: 'memo-0001',
        revisionNumber: 2,
        content: '把 design-core 的三层 token 接到了真实数据层，同步游标第一次跑通',
        tags: ['设计系统', '迁移'],
        aiSummary: null,
        createdAt: T(7),
      },
    ],
    deletions: { memo: [], diary: [], resource: [], bot: [] },
  }
}
seed()

// ---------------------------------------------------------------- helpers --

const now = () => Date.now()
const uuid = () => crypto.randomUUID()

function logRequest(method, path, status) {
  if (!LOG_PATH) return
  try {
    fs.appendFileSync(LOG_PATH, `${method} ${path} → ${status}\n`)
  } catch {
    /* logging must never break the stub */
  }
}

function send(res, status, body, headers = {}) {
  const payload =
    body === undefined || body === null
      ? Buffer.alloc(0)
      : Buffer.isBuffer(body)
        ? body
        : Buffer.from(JSON.stringify(body))
  res.writeHead(status, {
    'Content-Type': Buffer.isBuffer(body) ? headers['Content-Type'] || 'application/octet-stream' : 'application/json; charset=utf-8',
    ...headers,
  })
  res.end(payload)
  return status
}

const error = (res, status, message) =>
  send(res, status, { error: `${status} ${status === 401 ? 'Unauthorized' : status === 404 ? 'Not Found' : status === 400 ? 'Bad Request' : 'Internal Server Error'}`, message })

function readBody(req) {
  return new Promise((resolve) => {
    let data = ''
    req.on('data', (c) => (data += c))
    req.on('end', () => {
      if (!data) return resolve({})
      try {
        resolve(JSON.parse(data))
      } catch {
        resolve(null)
      }
    })
  })
}

function bearer(req) {
  const h = req.headers['authorization'] || ''
  return h.startsWith('Bearer ') ? h.slice(7) : null
}

function auth(req) {
  const token = bearer(req)
  if (!token || !db.accessTokens.has(token)) return null
  return db.accessTokens.get(token)
}

const withResources = (m) => ({
  id: m.id,
  content: m.content,
  tags: m.tags,
  isArchived: m.isArchived,
  diaryDate: m.diaryDate,
  aiSummary: m.aiSummary,
  createdAt: m.createdAt,
  updatedAt: m.updatedAt,
  revisionCount: m.revisionCount,
  resources: db.resources.filter((r) => m.resourceIds.includes(r.id)),
})

const paginate = (list, query) => {
  const page = Math.max(1, Number(query.get('page') || 1))
  const pageSize = Math.max(1, Number(query.get('pageSize') || 20))
  const items = list.slice((page - 1) * pageSize, page * pageSize)
  return { items, total: list.length, page, pageSize, totalPages: Math.ceil(list.length / pageSize) || 1 }
}

const byDate = (ts) => new Date(ts).toISOString().slice(0, 10)

// ---------------------------------------------------------------- routes ---

async function route(req, res) {
  const u = new URL(req.url, 'http://localhost')
  const p = u.pathname
  const q = u.searchParams
  const method = req.method

  // ---- health (no auth) ----
  if (p === '/health' && method === 'GET') return send(res, 200, { status: 'ok', version: '0.1.0-stub' })

  // ---- test hooks ----
  if (p === '/__stub/reset' && method === 'POST') {
    seed()
    return send(res, 200, { message: 'reset' })
  }
  if (p === '/__stub/inject' && method === 'POST') {
    const body = await readBody(req)
    if (!body?.content) return error(res, 400, 'content required')
    const memo = {
      id: uuid(),
      content: body.content,
      tags: body.tags || [],
      isArchived: false,
      diaryDate: null,
      aiSummary: null,
      createdAt: now(),
      updatedAt: now(),
      revisionCount: 1,
      resourceIds: [],
    }
    db.memos.push(memo)
    return send(res, 200, withResources(memo))
  }

  // ---- auth ----
  if (p === '/api/auth/login' && method === 'POST') {
    const body = await readBody(req)
    if (!body || body.username !== db.user.username || body.password !== db.password) {
      return error(res, 401, '用户名或密码错误')
    }
    const access = `access-${uuid()}`
    const refresh = `refresh-${uuid()}`
    db.accessTokens.set(access, { userId: db.user.id })
    db.refreshTokens.set(refresh, db.user.id)
    return send(res, 200, { accessToken: access, refreshToken: refresh, user: db.user })
  }

  if (p === '/api/auth/refresh' && method === 'POST') {
    const body = await readBody(req)
    const old = body?.refreshToken
    if (!old || !db.refreshTokens.has(old)) return error(res, 401, 'Invalid refresh token')
    // rotation: old access tokens issued for this refresh are revoked
    const userId = db.refreshTokens.get(old)
    db.refreshTokens.delete(old)
    for (const [t, v] of db.accessTokens) if (v.userId === userId && v.rotatable) db.accessTokens.delete(t)
    const access = `access-${uuid()}`
    const refresh = `refresh-${uuid()}`
    db.accessTokens.set(access, { userId, rotatable: true })
    db.refreshTokens.set(refresh, userId)
    return send(res, 200, { accessToken: access, refreshToken: refresh })
  }

  if (p === '/api/auth/me' && method === 'GET') {
    const session = auth(req)
    if (!session) return error(res, 401, 'Invalid token')
    return send(res, 200, db.user)
  }

  // ---- everything below requires Bearer ----
  const session = auth(req)
  if (!session) return error(res, 401, 'Invalid token')

  // ---- memos ----
  if (p === '/api/memos' && method === 'POST') {
    const body = await readBody(req)
    if (!body?.content) return error(res, 400, 'content is required')
    const ts = now()
    const memo = {
      id: uuid(),
      content: body.content,
      tags: body.tags || [],
      isArchived: false,
      diaryDate: body.diaryDate || null,
      aiSummary: body.aiSummary || null,
      createdAt: ts,
      updatedAt: ts,
      revisionCount: 1,
      resourceIds: body.resourceIds || [],
    }
    db.memos.push(memo)
    return send(res, 200, withResources(memo))
  }

  if (p === '/api/memos' && method === 'GET') {
    let list = [...db.memos]
    const archived = q.get('archived')
    if (archived !== null) list = list.filter((m) => m.isArchived === (archived === 'true'))
    const diaryDate = q.get('diaryDate')
    if (diaryDate) list = list.filter((m) => m.diaryDate === diaryDate)
    const search = q.get('search')
    if (search) list = list.filter((m) => m.content.includes(search) || m.tags.some((t) => t.includes(search)))
    list.sort((a, b) => b.createdAt - a.createdAt)
    return send(res, 200, paginate(list.map(withResources), q))
  }

  if (p === '/api/memos/search' && method === 'GET') {
    const query = q.get('query') || ''
    const tags = q.getAll('tags[]').concat(q.getAll('tags'))
    let list = db.memos.filter((m) => !query || m.content.includes(query) || m.tags.some((t) => t.includes(query)))
    if (tags.length) list = list.filter((m) => tags.every((t) => m.tags.includes(t)))
    const startDate = q.get('startDate')
    const endDate = q.get('endDate')
    if (startDate) list = list.filter((m) => byDate(m.createdAt) >= startDate)
    if (endDate) list = list.filter((m) => byDate(m.createdAt) <= endDate)
    const isArchived = q.get('isArchived')
    if (isArchived !== null) list = list.filter((m) => m.isArchived === (isArchived === 'true'))
    list.sort((a, b) => b.createdAt - a.createdAt)
    const page = Math.max(1, Number(q.get('page') || 1))
    const pageSize = Math.max(1, Number(q.get('pageSize') || 50))
    const memos = list.slice((page - 1) * pageSize, page * pageSize).map((m) => ({
      ...withResources(m),
      semanticScore: null,
      keywordScore: 1,
      matchType: 'keyword',
    }))
    return send(res, 200, { memos, total: list.length, page, pageSize, semanticEnabled: false })
  }

  if (p === '/api/memos/tags' && method === 'GET') {
    const counts = new Map()
    for (const m of db.memos) for (const t of m.tags) counts.set(t, (counts.get(t) || 0) + 1)
    return send(res, 200, [...counts.entries()].map(([tag, count]) => ({ tag, count })))
  }

  let m = p.match(/^\/api\/memos\/date\/(\d{4}-\d{2}-\d{2})$/)
  if (m && method === 'GET') {
    const date = m[1]
    const archived = q.get('archived')
    let list = db.memos.filter((x) => x.diaryDate === date || byDate(x.createdAt) === date)
    if (archived !== null) list = list.filter((x) => x.isArchived === (archived === 'true'))
    list.sort((a, b) => b.createdAt - a.createdAt)
    return send(res, 200, list.map(withResources))
  }

  m = p.match(/^\/api\/memos\/([^/]+)$/)
  if (m) {
    const memo = db.memos.find((x) => x.id === m[1])
    if (!memo) return error(res, 404, 'memo not found')
    if (method === 'GET') return send(res, 200, withResources(memo))
    if (method === 'PUT') {
      const body = await readBody(req)
      if (body === null) return error(res, 400, 'invalid json')
      if ('content' in body) memo.content = body.content
      if ('tags' in body) memo.tags = body.tags
      if ('resourceIds' in body) memo.resourceIds = body.resourceIds
      if ('isArchived' in body) memo.isArchived = body.isArchived
      if ('diaryDate' in body) memo.diaryDate = body.diaryDate
      if ('aiSummary' in body) memo.aiSummary = body.aiSummary
      memo.updatedAt = now()
      return send(res, 200, withResources(memo))
    }
    if (method === 'DELETE') {
      db.memos = db.memos.filter((x) => x.id !== memo.id)
      db.revisions = db.revisions.filter((x) => x.memoId !== memo.id)
      db.deletions.memo.push({ id: memo.id, deletedAt: now() })
      return send(res, 200)
    }
  }

  m = p.match(/^\/api\/memos\/([^/]+)\/detail$/)
  if (m && method === 'GET') {
    const memo = db.memos.find((x) => x.id === m[1])
    if (!memo) return error(res, 404, 'memo not found')
    return send(res, 200, {
      memo: withResources(memo),
      revisions: db.revisions.filter((r) => r.memoId === memo.id).sort((a, b) => b.revisionNumber - a.revisionNumber),
      botReplies: db.botReplies.filter((r) => r.memoId === memo.id),
    })
  }

  m = p.match(/^\/api\/memos\/([^/]+)\/revisions$/)
  if (m && method === 'GET') {
    const memo = db.memos.find((x) => x.id === m[1])
    if (!memo) return error(res, 404, 'memo not found')
    return send(res, 200, db.revisions.filter((r) => r.memoId === memo.id).sort((a, b) => b.revisionNumber - a.revisionNumber))
  }

  m = p.match(/^\/api\/memos\/([^/]+)\/archive$/)
  if (m && method === 'PUT') {
    const memo = db.memos.find((x) => x.id === m[1])
    if (!memo) return error(res, 404, 'memo not found')
    const body = await readBody(req)
    memo.isArchived = true
    if (body?.diaryDate) memo.diaryDate = body.diaryDate
    memo.updatedAt = now()
    return send(res, 200, withResources(memo))
  }

  m = p.match(/^\/api\/memos\/([^/]+)\/unarchive$/)
  if (m && method === 'PUT') {
    const memo = db.memos.find((x) => x.id === m[1])
    if (!memo) return error(res, 404, 'memo not found')
    memo.isArchived = false
    memo.updatedAt = now()
    return send(res, 200, withResources(memo))
  }

  m = p.match(/^\/api\/memos\/([^/]+)\/bot-replies$/)
  if (m && method === 'GET') {
    return send(res, 200, db.botReplies.filter((r) => r.memoId === m[1]))
  }

  // ---- diaries ----
  if (p === '/api/diaries' && method === 'GET') {
    let list = [...db.diaries]
    const startDate = q.get('startDate')
    const endDate = q.get('endDate')
    if (startDate) list = list.filter((d) => d.date >= startDate)
    if (endDate) list = list.filter((d) => d.date <= endDate)
    list.sort((a, b) => (a.date < b.date ? 1 : -1))
    return send(res, 200, paginate(list, q))
  }

  m = p.match(/^\/api\/diaries\/(\d{4}-\d{2}-\d{2})$/)
  if (m) {
    const date = m[1]
    let diary = db.diaries.find((d) => d.date === date)
    if (method === 'GET') {
      if (!diary) return error(res, 404, 'diary not found')
      const memos = db.memos
        .filter((x) => x.diaryDate === date || byDate(x.createdAt) === date)
        .sort((a, b) => b.createdAt - a.createdAt)
        .map(withResources)
      return send(res, 200, { ...diary, memos })
    }
    if (method === 'POST' || method === 'PUT') {
      const body = await readBody(req)
      if (!diary) {
        const ts = now()
        diary = {
          date,
          summary: '',
          moodKey: 'neutral',
          moodScore: 50,
          generationSource: 'manual',
          autoGenerationLocked: false,
          generatedFromMemoIds: [],
          lastAutoGeneratedAt: null,
          createdAt: ts,
          updatedAt: ts,
        }
        db.diaries.push(diary)
      }
      if (method === 'POST') {
        if ('summary' in body) diary.summary = body.summary
        if ('moodKey' in body) diary.moodKey = body.moodKey
        if ('moodScore' in body) diary.moodScore = body.moodScore
      } else {
        if ('summary' in body) diary.summary = body.summary
        if ('moodKey' in body) diary.moodKey = body.moodKey
        if ('moodScore' in body) diary.moodScore = body.moodScore
      }
      diary.updatedAt = now()
      const memos = db.memos.filter((x) => x.diaryDate === date || byDate(x.createdAt) === date).map(withResources)
      return send(res, 200, { ...diary, memos })
    }
  }

  // ---- resources ----
  if (p === '/api/resources' && method === 'GET') {
    return send(res, 200, paginate([...db.resources], q))
  }

  m = p.match(/^\/api\/resources\/([^/]+)\/(download|thumbnail)$/)
  if (m && method === 'GET') {
    const r = db.resources.find((x) => x.id === m[1])
    if (!r) return error(res, 404, 'resource not found')
    return send(res, 200, png1x1, { 'Content-Type': r.mimeType })
  }

  m = p.match(/^\/api\/resources\/([^/]+)$/)
  if (m && method === 'DELETE') {
    const r = db.resources.find((x) => x.id === m[1])
    if (!r) return error(res, 404, 'resource not found')
    db.resources = db.resources.filter((x) => x.id !== r.id)
    db.deletions.resource.push({ id: r.id, deletedAt: now() })
    return send(res, 200)
  }

  // ---- bots ----
  if (p === '/api/bots' && method === 'GET') {
    return send(res, 200, [...db.bots].sort((a, b) => a.sortOrder - b.sortOrder))
  }

  m = p.match(/^\/api\/bots\/([^/]+)$/)
  if (m && method === 'PUT') {
    const bot = db.bots.find((x) => x.id === m[1])
    if (!bot) return error(res, 404, 'bot not found')
    const body = await readBody(req)
    if ('autoReply' in body) bot.autoReply = body.autoReply
    if ('name' in body) bot.name = body.name
    if ('description' in body) bot.description = body.description
    bot.updatedAt = now()
    return send(res, 200, bot)
  }

  // ---- sync ----
  if (p === '/api/sync/pull' && method === 'POST') {
    const body = await readBody(req)
    if (!body || typeof body.clientId !== 'string') return error(res, 400, 'clientId required')
    const cursors = body.cursors || {}
    const cap = 200
    const pullEntity = (list, key, mapFn) => {
      const cursor = Number(cursors[key] || 0)
      const updated = list
        .filter((x) => x.updatedAt > cursor)
        .sort((a, b) => a.updatedAt - b.updatedAt)
        .slice(0, cap)
        .map(mapFn)
      const deletedIds = db.deletions[key] || []
      const deleted = deletedIds
        .filter((d) => d.deletedAt > cursor)
        .sort((a, b) => a.deletedAt - b.deletedAt)
        .slice(0, cap)
        .map((d) => d.id)
      const lastUpdated = updated.length ? updated[updated.length - 1].updatedAt : null
      const lastDeleted = deleted.length ? (db.deletions[key] || []).filter((d) => d.deletedAt > cursor).sort((a, b) => a.deletedAt - b.deletedAt)[Math.min(deleted.length, cap) - 1].deletedAt : null
      const candidates = [lastUpdated, lastDeleted, cursor > 0 ? cursor : 0].filter((v) => v !== null)
      const nextCursor = candidates.length ? Math.max(...candidates) : null
      return { updated, deletedIds: deleted, cursor: nextCursor }
    }
    const memoPull = pullEntity(db.memos, 'memo', withResources)
    const diaryPull = pullEntity(db.diaries, 'diary', (d) => d)
    const resourcePull = pullEntity(db.resources, 'resource', (r) => r)
    const botPull = pullEntity(db.bots, 'bot', (b) => b)
    const cursorsOut = {}
    if (memoPull.cursor !== null) cursorsOut.memo = memoPull.cursor
    if (diaryPull.cursor !== null) cursorsOut.diary = diaryPull.cursor
    if (resourcePull.cursor !== null) cursorsOut.resource = resourcePull.cursor
    if (botPull.cursor !== null) cursorsOut.bot = botPull.cursor
    return send(res, 200, {
      cursors: cursorsOut,
      changes: {
        memo: { updated: memoPull.updated, deletedIds: memoPull.deletedIds },
        diary: { updated: diaryPull.updated, deletedIds: diaryPull.deletedIds },
        resource: { updated: resourcePull.updated, deletedIds: resourcePull.deletedIds },
        bot: { updated: botPull.updated, deletedIds: botPull.deletedIds },
      },
    })
  }

  // ---- stats ----
  if (p === '/api/stats/heatmap' && method === 'GET') {
    const startDate = q.get('startDate')
    const endDate = q.get('endDate')
    const dates = []
    const counts = []
    const moods = []
    const moodScores = []
    if (startDate && endDate) {
      const d = new Date(`${startDate}T00:00:00Z`)
      const end = new Date(`${endDate}T00:00:00Z`)
      while (d <= end) {
        const date = d.toISOString().slice(0, 10)
        dates.push(date)
        counts.push(db.memos.filter((x) => byDate(x.createdAt) === date).length)
        const diary = db.diaries.find((x) => x.date === date)
        moods.push(diary ? diary.moodKey : null)
        moodScores.push(diary ? diary.moodScore : null)
        d.setUTCDate(d.getUTCDate() + 1)
      }
    }
    return send(res, 200, { dates, counts, moods, moodScores })
  }

  return error(res, 404, `no route: ${method} ${p}`)
}

const server = http.createServer((req, res) => {
  const path = req.url.split('?')[0]
  Promise.resolve()
    .then(() => route(req, res))
    .then((status) => logRequest(req.method, req.url, status ?? 200))
    .catch((e) => {
      const status = error(res, 500, String(e && e.message ? e.message : e))
      logRequest(req.method, path, status)
    })
})

server.listen(PORT, '0.0.0.0', () => {
  console.log(`[mosaic-stub] listening on http://0.0.0.0:${PORT} (log: ${LOG_PATH || 'off'})`)
})
