package store

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/crayonlu/mosaic/server-go/internal/domain"
)

const diaryColumns = `date, user_id, summary, mood_key, mood_score,
	generation_source, auto_generation_locked, generated_from_memo_ids,
	last_auto_generated_at, created_at, updated_at, is_deleted`

// DiaryStore reads and writes diaries and the memos archived against them.
type DiaryStore struct {
	pool *pgxpool.Pool
}

func NewDiaryStore(pool *pgxpool.Pool) *DiaryStore {
	return &DiaryStore{pool: pool}
}

// scanDiary reads the shared diary column list. The generated memo ids are
// stored as JSONB and decoded into UUIDs, matching the previous server.
func scanDiary(row pgx.Row) (domain.Diary, error) {
	var (
		date    time.Time
		memoIDs []byte
		diary   domain.Diary
	)
	err := row.Scan(
		&date,
		&diary.UserID,
		&diary.Summary,
		&diary.MoodKey,
		&diary.MoodScore,
		&diary.GenerationSource,
		&diary.AutoGenerationLocked,
		&memoIDs,
		&diary.LastAutoGeneratedAt,
		&diary.CreatedAt,
		&diary.UpdatedAt,
		&diary.IsDeleted,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Diary{}, domain.ErrNoRows
	}
	if err != nil {
		return domain.Diary{}, err
	}

	diary.Date = domain.NewDate(date)
	diary.GeneratedFromMemoIDs = decodeDiaryMemoIDs(memoIDs)
	return diary, nil
}

func decodeDiaryMemoIDs(raw []byte) []uuid.UUID {
	ids := []uuid.UUID{}
	if len(raw) == 0 {
		return ids
	}
	if err := json.Unmarshal(raw, &ids); err != nil {
		return []uuid.UUID{}
	}
	return ids
}

func diaryDateValue(date domain.Date) time.Time {
	return date.Time
}

func diaryDatePointer(date *domain.Date) *time.Time {
	if date == nil {
		return nil
	}
	value := date.Time
	return &value
}

// List returns one page of diaries plus the total before pagination.
func (s *DiaryStore) List(
	ctx context.Context,
	userID uuid.UUID,
	page, pageSize uint32,
	start, end *domain.Date,
) ([]domain.Diary, int64, error) {
	offset := int64(page-1) * int64(pageSize)
	rows, err := s.pool.Query(ctx,
		`SELECT `+diaryColumns+`
		 FROM diaries
		 WHERE user_id = $1
		   AND ($2::date IS NULL OR date >= $2)
		   AND ($3::date IS NULL OR date <= $3)
		 ORDER BY date DESC
		 LIMIT $4 OFFSET $5`,
		userID, diaryDatePointer(start), diaryDatePointer(end), int64(pageSize), offset)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	diaries := []domain.Diary{}
	for rows.Next() {
		diary, err := scanDiary(rows)
		if err != nil {
			return nil, 0, err
		}
		diaries = append(diaries, diary)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}

	var total int64
	err = s.pool.QueryRow(ctx,
		`SELECT COUNT(*) FROM diaries
		 WHERE user_id = $1
		   AND ($2::date IS NULL OR date >= $2)
		   AND ($3::date IS NULL OR date <= $3)`,
		userID, diaryDatePointer(start), diaryDatePointer(end)).Scan(&total)
	if err != nil {
		return nil, 0, err
	}
	return diaries, total, nil
}

// ByDate looks up one day's diary.
func (s *DiaryStore) ByDate(
	ctx context.Context,
	userID uuid.UUID,
	date domain.Date,
) (domain.Diary, error) {
	return scanDiary(s.pool.QueryRow(ctx,
		`SELECT `+diaryColumns+` FROM diaries WHERE date = $1 AND user_id = $2`,
		diaryDateValue(date), userID))
}

// MemosForDate returns the archived, non-deleted memos assigned to a day.
func (s *DiaryStore) MemosForDate(
	ctx context.Context,
	userID uuid.UUID,
	date domain.Date,
) ([]domain.Memo, error) {
	rows, err := s.pool.Query(ctx,
		`SELECT id, user_id, content, tags, is_archived, is_deleted, diary_date,
		        ai_summary, created_at, updated_at, revision_count
		 FROM memos
		 WHERE user_id = $1 AND diary_date = $2 AND is_deleted = false AND is_archived = true
		 ORDER BY created_at ASC`,
		userID, diaryDateValue(date))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	memos := []domain.Memo{}
	for rows.Next() {
		memo, err := scanDiaryMemo(rows)
		if err != nil {
			return nil, err
		}
		memos = append(memos, memo)
	}
	return memos, rows.Err()
}

func scanDiaryMemo(row pgx.Row) (domain.Memo, error) {
	var (
		memo      domain.Memo
		tags      []byte
		diaryDate *time.Time
	)
	err := row.Scan(
		&memo.ID,
		&memo.UserID,
		&memo.Content,
		&tags,
		&memo.IsArchived,
		&memo.IsDeleted,
		&diaryDate,
		&memo.AiSummary,
		&memo.CreatedAt,
		&memo.UpdatedAt,
		&memo.RevisionCount,
	)
	if err != nil {
		return domain.Memo{}, err
	}
	memo.Tags = domain.TagListFromJSON(tags)
	if diaryDate != nil {
		parsed := domain.NewDate(*diaryDate)
		memo.DiaryDate = &parsed
	}
	return memo, nil
}

// MemoResources returns the live attachments of a memo.
func (s *DiaryStore) MemoResources(ctx context.Context, memoID uuid.UUID) ([]domain.Resource, error) {
	rows, err := s.pool.Query(ctx,
		`SELECT id, memo_id, user_id, filename, resource_type, mime_type, file_size,
		        storage_type, storage_path, metadata, is_deleted, ai_description, created_at, updated_at
		 FROM resources WHERE memo_id = $1 AND is_deleted = FALSE ORDER BY created_at ASC`,
		memoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	resources := []domain.Resource{}
	for rows.Next() {
		resource, err := scanDiaryResource(rows)
		if err != nil {
			return nil, err
		}
		resources = append(resources, resource)
	}
	return resources, rows.Err()
}

func scanDiaryResource(row pgx.Row) (domain.Resource, error) {
	var (
		resource domain.Resource
		metadata []byte
	)
	err := row.Scan(
		&resource.ID,
		&resource.MemoID,
		&resource.UserID,
		&resource.Filename,
		&resource.Type,
		&resource.MimeType,
		&resource.FileSize,
		&resource.StorageType,
		&resource.StoragePath,
		&metadata,
		&resource.IsDeleted,
		&resource.AiDescription,
		&resource.CreatedAt,
		&resource.UpdatedAt,
	)
	if err != nil {
		return domain.Resource{}, err
	}
	resource.Metadata = decodeResourceMetadata(metadata)
	return resource, nil
}

func decodeResourceMetadata(raw []byte) map[string]any {
	if len(raw) == 0 {
		return map[string]any{}
	}
	metadata := map[string]any{}
	if err := json.Unmarshal(raw, &metadata); err != nil {
		return map[string]any{}
	}
	return metadata
}

// Upsert inserts or overwrites a day's diary. A manual write always unlocks
// automatic generation, matching the previous server.
func (s *DiaryStore) Upsert(
	ctx context.Context,
	userID uuid.UUID,
	date domain.Date,
	summary, moodKey string,
	moodScore int32,
	now int64,
) (domain.Diary, error) {
	var exists bool
	err := s.pool.QueryRow(ctx,
		`SELECT EXISTS (SELECT 1 FROM diaries WHERE date = $1 AND user_id = $2)`,
		diaryDateValue(date), userID).Scan(&exists)
	if err != nil {
		return domain.Diary{}, err
	}

	if exists {
		return scanDiary(s.pool.QueryRow(ctx,
			`UPDATE diaries SET
			     summary = $1, mood_key = $2, mood_score = $3,
			     generation_source = 'manual', auto_generation_locked = true, updated_at = $4
			 WHERE date = $5 AND user_id = $6
			 RETURNING `+diaryColumns,
			summary, moodKey, moodScore, now, diaryDateValue(date), userID))
	}

	return scanDiary(s.pool.QueryRow(ctx,
		`INSERT INTO diaries (date, user_id, summary, mood_key, mood_score,
		     generation_source, auto_generation_locked, generated_from_memo_ids,
		     last_auto_generated_at, created_at, updated_at)
		 VALUES ($1, $2, $3, $4, $5, 'manual', true, '[]'::jsonb, NULL, $6, $6)
		 RETURNING `+diaryColumns,
		diaryDateValue(date), userID, summary, moodKey, moodScore, now))
}

// Update applies whichever fields were supplied and locks auto generation.
func (s *DiaryStore) Update(
	ctx context.Context,
	userID uuid.UUID,
	date domain.Date,
	summary, moodKey *string,
	moodScore *int32,
	now int64,
) (domain.Diary, error) {
	return scanDiary(s.pool.QueryRow(ctx,
		`UPDATE diaries SET
		     updated_at = $1,
		     summary = COALESCE($2, summary),
		     mood_key = COALESCE($3, mood_key),
		     mood_score = COALESCE($4, mood_score),
		     generation_source = 'manual', auto_generation_locked = true
		 WHERE date = $5 AND user_id = $6
		 RETURNING `+diaryColumns,
		now, summary, moodKey, moodScore, diaryDateValue(date), userID))
}
